service: github-automation-project

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-rgehan

plugins:
  - serverless-offline

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post
